package controller;

public enum Requests {

	ASK_FOR_CLIENT_CONCERTS, SERVER_TO_CLIENT_CONCERTS, CLIENT_ASK_FOR_TICKETS,SERVER_TICKETS_TO_CLIENT,
	ASK_FOR_TICKETS_PURCHASE, TICKETS_PURCHASE_RESPONSE, PURCHASE_COMPLETED, PURCHASE_ERROR, UPDATE_30, FULL_DATA_TO_ADMIN, CLIENT_ASK_FOR_TICKETS_2;
	
}
